# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:pAYQod3c/U4QfQ==,iv:v3PYDV3J6MAzDchzWNmd2JT/YOZvdrxJeP+cD//fjmo=,tag:5t0KI06vIARvK4UOJDDh+g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:6q5db8Hi2B0yxSzi7FpF6Bhc,iv:zrJnKdj3dk2pwMr8YGngV40SHHOf6Zo46MZ5VFLOWyk=,tag:/NgRnceXmEyXwHW/A2dBsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-16T01:19:29Z"
    mac: ENC[AES256_GCM,data:MabwS7YsI4Vq8IGzjnow/HyYQ2aa3b1l2Y6B4fre4GQLVIsCiFr+DS1/j6yS54+7i+kQ97XgJSQRv4nflFUEeUPS4lyZtEuTRKHHn/q+nEldgINVhSsN4qYrV+TqH88Q+14+8RApqHdB6nSkJPG/0fd51b19C7uHGTObXwUI7Vk=,iv:iIzR4SV4VpXCRRgjT5rTalmriJCRybh5GSVvufqytv8=,tag:WnBS8bIiGxCay+3nGNjHkQ==,type:str]
    pgp:
        - created_at: "2021-08-16T01:19:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3iwTtPPgM6CAQ/+O1Ar9ODBE6qkG4NUYFbOMUTs0AXJWBDeM4McDF+h8BnE
            jgoDwJ+q4e/T3bmCAOfBw9B2ejfS1nvkJXl+2zSD6TF+n4SkTL1HHY/1Jvk/G7Ob
            6qm6w17LFm/wj4x7RyKSXQxiZ+h+z9SWP0rNHPeW+EZuW3EVpTk6uoopvdJI9x0M
            QMpYkKZm77jnknr2U9Ua1Bt4PXH0RLpR/9adFzVcMvlgRtaPk/EyQoFRWkkpf1Xt
            57aOqX2ZYDNfIZxAyYbEVg/KOC1Py5/c5UJ8dSPNB7nCfiUdvq7g82k7s+9QHXoM
            08MFSecMaci5DW2CyoZ9LjE/g+DVZSFlEzzHLCB4d82tGbea6eT8/oF4Td5n/mnV
            xZFmB1jwV99mqxDvPi9tizpNenyWGNQa1076XhKPtcKgRj97CRT2hWz/yp1xOXbA
            hEPGE859GdfKYqpYlALU/hmnD3TvcIEVqquR9AbBr8iG7GmJ+j8Ia5ssFGN7ykEX
            oTYyK2BeohAP+5q4xxXQUsYLIMFREBAgz1XHNCGIv7GlsR0Aq1ZdR2x6Gykq/SHz
            coyRNZ0iZDTG7LIeSXZJVX3SYqCNhp89IaQKyonBg8hpkBjpV5PWe/xgkV2tgKLS
            dcy4UTon+GXqzu/xLmdrPBBCjMBn1TUwhSgA416zKpp+hMLSnRteVxtg090jYBXS
            XgH7I+z8c9GLYzQR65CA1YZNqai2/G4+5WwxbkeyJvqW0Ub4Grrf8cczKJLWWF9D
            vq8LbVa/zJzRJuY/k284TuUOGf7zr1Ra26B/QaR/GhjfOShxvtceavnrF4wgRw0=
            =BiLC
            -----END PGP MESSAGE-----
          fp: C474DDDD27EBB48FB2238D6136A7D21E4995238C
        - created_at: "2021-08-16T01:19:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9NCCA3w5tVPAQ/+MYInGNaI5aHY9DWHyf6vZNtZ+Rnx4VswT99Jc3Besg3d
            zTBL9OPs9nQFKbO6wAG1vFQGA54v3PbPNI809QLsyIhnjV3sXzkkBtk8ZAwbXRG7
            dMYUnI+G9zdJ25kypKUsmSVagfqs3CJU+cECHzB/5Q7MjQ4UOvsbhSB1s+TBziQZ
            v6T01mrNPty/soFPm3r1Sz4rG/yJJ3+TW/KijxsiEfbO3ZaZ83zWqheKJvwtnx6k
            6wP30ZwrbB29eD4+2GQEZfwyivErkoq/T0BwKxJ+V5g9GWis7/RAk8DFglccma8b
            yJxGVpTIpHSWrsVDpIqlXJcIu9wKkH8bwNNuDzxzt6cjfISOCJT+dM+NaBDwwind
            SJdqlO1gN8TEtG923DRhrKPkpxjCfD1fhl2mf+0sVYp+ikdTEZUm6e1qSkB0mUDZ
            znOkNIHrlyPlfx1xcrlyR4/RqA1ROGucSYML//QdHc/5OJzmddUPoCJOXtklBcFs
            aED5FvfZ6RJ5YmD/s8lCkq5w3xP1HQO+iy4t8E+slBIrf959GG1ofJG7z+W5s6zA
            G0wr5DT+PNii0XxWOuF1iFm+ld3P1d4d2l3diHyomrnaNO+/0XxAP+knEB8nN49S
            hR4lVo6heZ4fLGXIYBjcFaa/vmw4COzyb2fG+A36Vz8DnYGBH8jMy5mfUq8shobS
            XgFX7322jHUmFxImN5v4OZfRFjX9AhfIoN5CLT/cc8h+goxITwbRXa4hvj+0wdX6
            bMcFTh22L6hQNToKNScwiyl/JGO3X8wpVSu3e6TntJQcBpOPxfpd5QBADSG3rwU=
            =/IWE
            -----END PGP MESSAGE-----
          fp: C87AAFC6FD7EB23BDFC184BEBF25B91C6A81ECC6
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
